In [1]:
import numpy as np
import pandas as pd

In [3]:
# if pandas and numpy ki libraries nahi aye and code mai error aye then write this
# pip install pandas
# pip install numpy

In [5]:
data = np.arange(12)  # arange mai jo number app pass krenge utne numbers ka array de dega
# arange is funcn jo input le ga which is a number of length and then array dega utne numbers ka

In [165]:
data = np.arange(24).reshape(4,6)  # reshape mai woh value aegi jo product dega apke arange ka means arange 24 and reshape 4*6=24, 

In [167]:
data

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [17]:
type(data)

numpy.ndarray

In [19]:
data.shape

(4, 6)

In [21]:
data.ndim

2

In [29]:
data1= np.arange(30,60).reshape(5,6)

In [31]:
data1

array([[30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [45]:
data1.ndim

2

In [47]:
data2=np.linspace(20,10,4) # when you want to split your data you use linspace
# linspace data ko equal parts mai distribute krta ha 

In [49]:
data2

array([20.        , 16.66666667, 13.33333333, 10.        ])

In [51]:
np.random.randint(10)

7

In [ ]:
#dataframe mai jab tk indexes nahi honge then its not a dataframe
#dataframe is composed of 2 things series and index and indices.means rows and columns and index.

In [61]:
df=pd.DataFrame(data1,index=['Row1','Row2','Row3','Row4','Row5'],
                columns=['column1','column2','column3','column4','column5','column6'])

In [63]:
df

column1  column2  column3  column4  column5  column6
Row1       30       31       32       33       34       35
Row2       36       37       38       39       40       41
Row3       42       43       44       45       46       47
Row4       48       49       50       51       52       53
Row5       54       55       56       57       58       59

In [ ]:
#pandas mai tabular data mai kaam krte hain.

In [65]:
# 3 basic funcns in pandas

In [67]:
df.columns #gives all the columns in the the dataframe

Index(['column1', 'column2', 'column3', 'column4', 'column5', 'column6'], dtype='object')

In [69]:
df.shape # tells 5 rows and 6 columns

(5, 6)

In [71]:
df.head() # head will retrieve first five rows in a data

column1  column2  column3  column4  column5  column6
Row1       30       31       32       33       34       35
Row2       36       37       38       39       40       41
Row3       42       43       44       45       46       47
Row4       48       49       50       51       52       53
Row5       54       55       56       57       58       59

In [73]:
df.tail() # tail will retrieve last 5 rows in data

column1  column2  column3  column4  column5  column6
Row1       30       31       32       33       34       35
Row2       36       37       38       39       40       41
Row3       42       43       44       45       46       47
Row4       48       49       50       51       52       53
Row5       54       55       56       57       58       59

In [83]:
df.sample(3)

column1  column2  column3  column4  column5  column6
Row4       48       49       50       51       52       53
Row5       54       55       56       57       58       59
Row2       36       37       38       39       40       41

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   column1  5 non-null      int32
 1   column2  5 non-null      int32
 2   column3  5 non-null      int32
 3   column4  5 non-null      int32
 4   column5  5 non-null      int32
 5   column6  5 non-null      int32
dtypes: int32(6)
memory usage: 160.0+ bytes


In [91]:
df.describe() # gives descriptive summary of those columns jin ki datad type numeric ha (float&int)

column1    column2    column3    column4    column5    column6
count   5.000000   5.000000   5.000000   5.000000   5.000000   5.000000
mean   42.000000  43.000000  44.000000  45.000000  46.000000  47.000000
std     9.486833   9.486833   9.486833   9.486833   9.486833   9.486833
min    30.000000  31.000000  32.000000  33.000000  34.000000  35.000000
25%    36.000000  37.000000  38.000000  39.000000  40.000000  41.000000
50%    42.000000  43.000000  44.000000  45.000000  46.000000  47.000000
75%    48.000000  49.000000  50.000000  51.000000  52.000000  53.000000
max    54.000000  55.000000  56.000000  57.000000  58.000000  59.000000

In [95]:
# Generating sample Google Play

data = {
    'App': [f'App_{i}' for i in range(1, 31)],
    'Category': np.random.choice(['Game', 'Productivity', 'Health', 'Education'], 30),
    'Rating': np.random.uniform(1.0, 5.0, 30).round(1),
    'Reviews': np.random.randint(1, 10000, 30),
    'Size': np.random.choice(['Varies with device', '10M', '20M', '30M'], 30),
    'Installs': np.random.choice(['1,000+', '10,000+', '50,000+', '100,000+'], 30),
    'Type': np.random.choice(['Free', 'Paid'], 30),
    'Price': np.random.choice(['0', '0.99', '1.99', '2.99', '4.99', '5.99', '9.99'], 30),
    'Content Rating': np.random.choice(['Everyone', 'Teen', 'Everyone 10+', 'Mature 17+'], 30)
}

In [97]:
data

{'App': ['App_1',
  'App_2',
  'App_3',
  'App_4',
  'App_5',
  'App_6',
  'App_7',
  'App_8',
  'App_9',
  'App_10',
  'App_11',
  'App_12',
  'App_13',
  'App_14',
  'App_15',
  'App_16',
  'App_17',
  'App_18',
  'App_19',
  'App_20',
  'App_21',
  'App_22',
  'App_23',
  'App_24',
  'App_25',
  'App_26',
  'App_27',
  'App_28',
  'App_29',
  'App_30'],
 'Category': array(['Productivity', 'Game', 'Health', 'Education', 'Productivity',
        'Game', 'Health', 'Game', 'Game', 'Game', 'Game', 'Game',
        'Education', 'Game', 'Health', 'Education', 'Education', 'Game',
        'Education', 'Productivity', 'Game', 'Game', 'Education', 'Game',
        'Productivity', 'Health', 'Game', 'Education', 'Health', 'Game'],
       dtype='<U12'),
 'Rating': array([1.3, 2.2, 2.8, 3.9, 4.5, 4.3, 1.8, 1.2, 1.5, 2.4, 3.2, 1.1, 4.2,
        3.1, 1.1, 3.8, 2.8, 3.5, 3. , 1.7, 3.4, 3.1, 4. , 5. , 2.2, 1.9,
        1.4, 2.7, 4.1, 1. ]),
 'Reviews': array([1026, 1925, 2420, 4525, 9477, 3473, 8575, 76

In [99]:
type(data)

dict

In [101]:
df=pd.DataFrame(data)

In [105]:
df

App      Category  Rating  Reviews                Size  Installs  Type  \
0    App_1  Productivity     1.3     1026                 20M  100,000+  Paid   
1    App_2          Game     2.2     1925  Varies with device   10,000+  Paid   
2    App_3        Health     2.8     2420  Varies with device    1,000+  Paid   
3    App_4     Education     3.9     4525                 30M   10,000+  Free   
4    App_5  Productivity     4.5     9477                 10M   10,000+  Free   
5    App_6          Game     4.3     3473                 10M   50,000+  Paid   
6    App_7        Health     1.8     8575                 30M  100,000+  Free   
7    App_8          Game     1.2     7662  Varies with device   50,000+  Free   
8    App_9          Game     1.5     9763                 30M    1,000+  Paid   
9   App_10          Game     2.4     5430                 30M  100,000+  Paid   
10  App_11          Game     3.2      250                 30M   10,000+  Free   
11  App_12          Game     1.1     7172  Varies with device   10,000+  Paid   
12  App_13     Education     4.2     9785                 20M   50,000+  Free   
13  App_14          Game     3.1     3884  Varies with device   10,000+  Free   
14  App_15        Health     1.1     1842                 10M   50,000+  Paid   
15  App_16     Education     3.8     6086  Varies with device   10,000+  Paid   
16  App_17     Education     2.8     5017                 30M   50,000+  Free   
17  App_18          Game     3.5      680                 20M   50,000+  Free   
18  App_19     Education     3.0     7756                 30M    1,000+  Free   
19  App_20  Productivity     1.7     6525  Varies with device    1,000+  Paid   
20  App_21          Game     3.4     6257                 20M    1,000+  Paid   
21  App_22          Game     3.1     8946                 20M   10,000+  Paid   
22  App_23     Education     4.0      450  Varies with device   50,000+  Paid   
23  App_24          Game     5.0     4943                 10M    1,000+  Paid   
24  App_25  Productivity     2.2     3048                 30M   10,000+  Free   
25  App_26        Health     1.9     2152                 10M   50,000+  Free   
26  App_27          Game     1.4     9048  Varies with device   50,000+  Free   
27  App_28     Education     2.7     5726                 20M    1,000+  Free   
28  App_29        Health     4.1     4916  Varies with device   50,000+  Free   
29  App_30          Game     1.0     4213                 10M   50,000+  Paid   

   Price Content Rating  
0   9.99           Teen  
1   5.99       Everyone  
2   1.99     Mature 17+  
3   2.99   Everyone 10+  
4   9.99           Teen  
5   4.99       Everyone  
6   4.99   Everyone 10+  
7   2.99   Everyone 10+  
8      0           Teen  
9   5.99       Everyone  
10     0   Everyone 10+  
11  2.99       Everyone  
12  9.99   Everyone 10+  
13  0.99       Everyone  
14     0     Mature 17+  
15  9.99       Everyone  
16  1.99   Everyone 10+  
17  2.99     Mature 17+  
18  2.99           Teen  
19  2.99     Mature 17+  
20  4.99       Everyone  
21  1.99           Teen  
22  9.99   Everyone 10+  
23     0           Teen  
24  1.99       Everyone  
25  5.99     Mature 17+  
26  2.99       Everyone  
27  4.99     Mature 17+  
28  2.99     Mature 17+  
29     0       Everyone

In [107]:
type(df)

pandas.core.frame.DataFrame

In [109]:
type(df.App)

pandas.core.series.Series

In [111]:
df.head()

App      Category  Rating  Reviews                Size  Installs  Type  \
0  App_1  Productivity     1.3     1026                 20M  100,000+  Paid   
1  App_2          Game     2.2     1925  Varies with device   10,000+  Paid   
2  App_3        Health     2.8     2420  Varies with device    1,000+  Paid   
3  App_4     Education     3.9     4525                 30M   10,000+  Free   
4  App_5  Productivity     4.5     9477                 10M   10,000+  Free   

  Price Content Rating  
0  9.99           Teen  
1  5.99       Everyone  
2  1.99     Mature 17+  
3  2.99   Everyone 10+  
4  9.99           Teen

In [113]:
df.tail()

App   Category  Rating  Reviews                Size Installs  Type  \
25  App_26     Health     1.9     2152                 10M  50,000+  Free   
26  App_27       Game     1.4     9048  Varies with device  50,000+  Free   
27  App_28  Education     2.7     5726                 20M   1,000+  Free   
28  App_29     Health     4.1     4916  Varies with device  50,000+  Free   
29  App_30       Game     1.0     4213                 10M  50,000+  Paid   

   Price Content Rating  
25  5.99     Mature 17+  
26  2.99       Everyone  
27  4.99     Mature 17+  
28  2.99     Mature 17+  
29     0       Everyone

In [115]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   App             30 non-null     object 
 1   Category        30 non-null     object 
 2   Rating          30 non-null     float64
 3   Reviews         30 non-null     int32  
 4   Size            30 non-null     object 
 5   Installs        30 non-null     object 
 6   Type            30 non-null     object 
 7   Price           30 non-null     object 
 8   Content Rating  30 non-null     object 
dtypes: float64(1), int32(1), object(7)
memory usage: 2.1+ KB


In [117]:
df.describe()

Rating      Reviews
count  30.000000    30.000000
mean    2.740000  5099.066667
std     1.171383  2967.786810
min     1.000000   250.000000
25%     1.725000  2577.000000
50%     2.800000  4980.000000
75%     3.725000  7539.500000
max     5.000000  9785.000000

In [119]:
df.sample()

App Category  Rating  Reviews                Size Installs  Type Price  \
26  App_27     Game     1.4     9048  Varies with device  50,000+  Free  2.99   

   Content Rating  
26       Everyone

In [121]:
df.sample(3)

App   Category  Rating  Reviews                Size Installs  Type  \
15  App_16  Education     3.8     6086  Varies with device  10,000+  Paid   
16  App_17  Education     2.8     5017                 30M  50,000+  Free   
29  App_30       Game     1.0     4213                 10M  50,000+  Paid   

   Price Content Rating  
15  9.99       Everyone  
16  1.99   Everyone 10+  
29     0       Everyone

In [123]:
df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating'],
      dtype='object')

In [125]:
df.shape

(30, 9)

In [133]:
df[['App','Price','Reviews']]  #always put 2 brackets[[  ]] for 2 dimension

App Price  Reviews
0    App_1  9.99     1026
1    App_2  5.99     1925
2    App_3  1.99     2420
3    App_4  2.99     4525
4    App_5  9.99     9477
5    App_6  4.99     3473
6    App_7  4.99     8575
7    App_8  2.99     7662
8    App_9     0     9763
9   App_10  5.99     5430
10  App_11     0      250
11  App_12  2.99     7172
12  App_13  9.99     9785
13  App_14  0.99     3884
14  App_15     0     1842
15  App_16  9.99     6086
16  App_17  1.99     5017
17  App_18  2.99      680
18  App_19  2.99     7756
19  App_20  2.99     6525
20  App_21  4.99     6257
21  App_22  1.99     8946
22  App_23  9.99      450
23  App_24     0     4943
24  App_25  1.99     3048
25  App_26  5.99     2152
26  App_27  2.99     9048
27  App_28  4.99     5726
28  App_29  2.99     4916
29  App_30     0     4213

In [135]:
df['Price'].unique()

array(['9.99', '5.99', '1.99', '2.99', '4.99', '0', '0.99'], dtype=object)

In [139]:
df['Size'].unique()

array(['20M', 'Varies with device', '30M', '10M'], dtype=object)

In [141]:
df['Type'].unique()

array(['Paid', 'Free'], dtype=object)

In [143]:
df['Rating'].unique()

array([1.3, 2.2, 2.8, 3.9, 4.5, 4.3, 1.8, 1.2, 1.5, 2.4, 3.2, 1.1, 4.2,
       3.1, 3.8, 3.5, 3. , 1.7, 3.4, 4. , 5. , 1.9, 1.4, 2.7, 4.1, 1. ])

In [145]:
df['Reviews'].unique()

array([1026, 1925, 2420, 4525, 9477, 3473, 8575, 7662, 9763, 5430,  250,
       7172, 9785, 3884, 1842, 6086, 5017,  680, 7756, 6525, 6257, 8946,
        450, 4943, 3048, 2152, 9048, 5726, 4916, 4213])

In [151]:
df.isnull()

App  Category  Rating  Reviews   Size  Installs   Type  Price  \
0   False     False   False    False  False     False  False  False   
1   False     False   False    False  False     False  False  False   
2   False     False   False    False  False     False  False  False   
3   False     False   False    False  False     False  False  False   
4   False     False   False    False  False     False  False  False   
5   False     False   False    False  False     False  False  False   
6   False     False   False    False  False     False  False  False   
7   False     False   False    False  False     False  False  False   
8   False     False   False    False  False     False  False  False   
9   False     False   False    False  False     False  False  False   
10  False     False   False    False  False     False  False  False   
11  False     False   False    False  False     False  False  False   
12  False     False   False    False  False     False  False  False   
13  False     False   False    False  False     False  False  False   
14  False     False   False    False  False     False  False  False   
15  False     False   False    False  False     False  False  False   
16  False     False   False    False  False     False  False  False   
17  False     False   False    False  False     False  False  False   
18  False     False   False    False  False     False  False  False   
19  False     False   False    False  False     False  False  False   
20  False     False   False    False  False     False  False  False   
21  False     False   False    False  False     False  False  False   
22  False     False   False    False  False     False  False  False   
23  False     False   False    False  False     False  False  False   
24  False     False   False    False  False     False  False  False   
25  False     False   False    False  False     False  False  False   
26  False     False   False    False  False     False  False  False   
27  False     False   False    False  False     False  False  False   
28  False     False   False    False  False     False  False  False   
29  False     False   False    False  False     False  False  False   

    Content Rating  
0            False  
1            False  
2            False  
3            False  
4            False  
5            False  
6            False  
7            False  
8            False  
9            False  
10           False  
11           False  
12           False  
13           False  
14           False  
15           False  
16           False  
17           False  
18           False  
19           False  
20           False  
21           False  
22           False  
23           False  
24           False  
25           False  
26           False  
27           False  
28           False  
29           False

In [155]:
df.isnull().sum() #gives k kis column mai kitni null values hain 

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
dtype: int64

In [157]:
df['Price'].unique()

array(['9.99', '5.99', '1.99', '2.99', '4.99', '0', '0.99'], dtype=object)

In [161]:
df['Price']=df['Price'].replace('Free','0') # changes the values of column price.

In [163]:
df['Price']

0     9.99
1     5.99
2     1.99
3     2.99
4     9.99
5     4.99
6     4.99
7     2.99
8        0
9     5.99
10       0
11    2.99
12    9.99
13    0.99
14       0
15    9.99
16    1.99
17    2.99
18    2.99
19    2.99
20    4.99
21    1.99
22    9.99
23       0
24    1.99
25    5.99
26    2.99
27    4.99
28    2.99
29       0
Name: Price, dtype: object