In [1]:
import numpy as np
import pandas as pd

In [5]:
df=pd.read_csv('iGpwgr.csv')
df.head()

App        Category  Rating  \
0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN     4.1   
1                                Coloring book moana  ART_AND_DESIGN     3.9   
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN     4.7   
3                              Sketch - Draw & Paint  ART_AND_DESIGN     4.5   
4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN     4.3   

  Reviews  Size     Installs  Type Price Content Rating  \
0     159   19M      10,000+  Free     0       Everyone   
1     967   14M     500,000+  Free     0       Everyone   
2   87510  8.7M   5,000,000+  Free     0       Everyone   
3  215644   25M  50,000,000+  Free     0           Teen   
4     967  2.8M     100,000+  Free     0       Everyone   

                      Genres      Last Updated         Current Ver  \
0               Art & Design   January 7, 2018               1.0.0   
1  Art & Design;Pretend Play  January 15, 2018               2.0.0   
2               Art & Design    August 1, 2018               1.2.4   
3               Art & Design      June 8, 2018  Varies with device   
4    Art & Design;Creativity     June 20, 2018                 1.1   

    Android Ver  
0  4.0.3 and up  
1  4.0.3 and up  
2  4.0.3 and up  
3    4.2 and up  
4    4.4 and up

In [9]:
df.info() # non-null column se pata chal jata hai k konse columns mai entries missing hain as we can see rating,type,current ver ki value is missing.
#total entries 10841 hain.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   App             10841 non-null  object 
 1   Category        10841 non-null  object 
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object 
 4   Size            10841 non-null  object 
 5   Installs        10841 non-null  object 
 6   Type            10840 non-null  object 
 7   Price           10841 non-null  object 
 8   Content Rating  10840 non-null  object 
 9   Genres          10841 non-null  object 
 10  Last Updated    10841 non-null  object 
 11  Current Ver     10833 non-null  object 
 12  Android Ver     10838 non-null  object 
dtypes: float64(1), object(12)
memory usage: 1.1+ MB


In [11]:
df.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [15]:
df['Price'].unique()

array(['0', '$4.99', '$3.99', '$6.99', '$1.49', '$2.99', '$7.99', '$5.99',
       '$3.49', '$1.99', '$9.99', '$7.49', '$0.99', '$9.00', '$5.49',
       '$10.00', '$24.99', '$11.99', '$79.99', '$16.99', '$14.99',
       '$1.00', '$29.99', '$12.99', '$2.49', '$10.99', '$1.50', '$19.99',
       '$15.99', '$33.99', '$74.99', '$39.99', '$3.95', '$4.49', '$1.70',
       '$8.99', '$2.00', '$3.88', '$25.99', '$399.99', '$17.99',
       '$400.00', '$3.02', '$1.76', '$4.84', '$4.77', '$1.61', '$2.50',
       '$1.59', '$6.49', '$1.29', '$5.00', '$13.99', '$299.99', '$379.99',
       '$37.99', '$18.99', '$389.99', '$19.90', '$8.49', '$1.75',
       '$14.00', '$4.85', '$46.99', '$109.99', '$154.99', '$3.08',
       '$2.59', '$4.80', '$1.96', '$19.40', '$3.90', '$4.59', '$15.46',
       '$3.04', '$4.29', '$2.60', '$3.28', '$4.60', '$28.99', '$2.95',
       '$2.90', '$1.97', '$200.00', '$89.99', '$2.56', '$30.99', '$3.61',
       '$394.99', '$1.26', 'Everyone', '$1.20', '$1.04'], dtype=object)

In [33]:
# replace everyone with 0 and then change the data type of column to float.
df['Price']=df['Price'].replace('Everyone','0')
df['Price']=df['Price'].str.replace('$','').astype(float)

In [35]:
df['Price'].unique()

array([  0.  ,   4.99,   3.99,   6.99,   1.49,   2.99,   7.99,   5.99,
         3.49,   1.99,   9.99,   7.49,   0.99,   9.  ,   5.49,  10.  ,
        24.99,  11.99,  79.99,  16.99,  14.99,   1.  ,  29.99,  12.99,
         2.49,  10.99,   1.5 ,  19.99,  15.99,  33.99,  74.99,  39.99,
         3.95,   4.49,   1.7 ,   8.99,   2.  ,   3.88,  25.99, 399.99,
        17.99, 400.  ,   3.02,   1.76,   4.84,   4.77,   1.61,   2.5 ,
         1.59,   6.49,   1.29,   5.  ,  13.99, 299.99, 379.99,  37.99,
        18.99, 389.99,  19.9 ,   8.49,   1.75,  14.  ,   4.85,  46.99,
       109.99, 154.99,   3.08,   2.59,   4.8 ,   1.96,  19.4 ,   3.9 ,
         4.59,  15.46,   3.04,   4.29,   2.6 ,   3.28,   4.6 ,  28.99,
         2.95,   2.9 ,   1.97, 200.  ,  89.99,   2.56,  30.99,   3.61,
       394.99,   1.26,   1.2 ,   1.04])

In [27]:
len(df['Price'].unique())

92

In [39]:
df.Price.dtype

dtype('float64')

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   App             10841 non-null  object 
 1   Category        10841 non-null  object 
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object 
 4   Size            10841 non-null  object 
 5   Installs        10841 non-null  object 
 6   Type            10840 non-null  object 
 7   Price           10841 non-null  float64
 8   Content Rating  10840 non-null  object 
 9   Genres          10841 non-null  object 
 10  Last Updated    10841 non-null  object 
 11  Current Ver     10833 non-null  object 
 12  Android Ver     10838 non-null  object 
dtypes: float64(2), object(11)
memory usage: 1.1+ MB


In [41]:
df.Installs.dtype

dtype('O')

In [43]:
df['Size'].unique()

array(['19M', '14M', '8.7M', '25M', '2.8M', '5.6M', '29M', '33M', '3.1M',
       '28M', '12M', '20M', '21M', '37M', '2.7M', '5.5M', '17M', '39M',
       '31M', '4.2M', '7.0M', '23M', '6.0M', '6.1M', '4.6M', '9.2M',
       '5.2M', '11M', '24M', 'Varies with device', '9.4M', '15M', '10M',
       '1.2M', '26M', '8.0M', '7.9M', '56M', '57M', '35M', '54M', '201k',
       '3.6M', '5.7M', '8.6M', '2.4M', '27M', '2.5M', '16M', '3.4M',
       '8.9M', '3.9M', '2.9M', '38M', '32M', '5.4M', '18M', '1.1M',
       '2.2M', '4.5M', '9.8M', '52M', '9.0M', '6.7M', '30M', '2.6M',
       '7.1M', '3.7M', '22M', '7.4M', '6.4M', '3.2M', '8.2M', '9.9M',
       '4.9M', '9.5M', '5.0M', '5.9M', '13M', '73M', '6.8M', '3.5M',
       '4.0M', '2.3M', '7.2M', '2.1M', '42M', '7.3M', '9.1M', '55M',
       '23k', '6.5M', '1.5M', '7.5M', '51M', '41M', '48M', '8.5M', '46M',
       '8.3M', '4.3M', '4.7M', '3.3M', '40M', '7.8M', '8.8M', '6.6M',
       '5.1M', '61M', '66M', '79k', '8.4M', '118k', '44M', '695k', '1.6M',
     

In [70]:
df['Size']=df['Size'].replace('Varies with device','0')
df['Size']=df['Size'].str.replace('M','')
df['Size']=df['Size'].str.replace('k','').str.replace('+','').str.replace(',','').astype(float)

In [72]:
df.Size.unique()

array([1.90e+01, 1.40e+01, 8.70e+00, 2.50e+01, 2.80e+00, 5.60e+00,
       2.90e+01, 3.30e+01, 3.10e+00, 2.80e+01, 1.20e+01, 2.00e+01,
       2.10e+01, 3.70e+01, 2.70e+00, 5.50e+00, 1.70e+01, 3.90e+01,
       3.10e+01, 4.20e+00, 7.00e+00, 2.30e+01, 6.00e+00, 6.10e+00,
       4.60e+00, 9.20e+00, 5.20e+00, 1.10e+01, 2.40e+01, 0.00e+00,
       9.40e+00, 1.50e+01, 1.00e+01, 1.20e+00, 2.60e+01, 8.00e+00,
       7.90e+00, 5.60e+01, 5.70e+01, 3.50e+01, 5.40e+01, 2.01e+02,
       3.60e+00, 5.70e+00, 8.60e+00, 2.40e+00, 2.70e+01, 2.50e+00,
       1.60e+01, 3.40e+00, 8.90e+00, 3.90e+00, 2.90e+00, 3.80e+01,
       3.20e+01, 5.40e+00, 1.80e+01, 1.10e+00, 2.20e+00, 4.50e+00,
       9.80e+00, 5.20e+01, 9.00e+00, 6.70e+00, 3.00e+01, 2.60e+00,
       7.10e+00, 3.70e+00, 2.20e+01, 7.40e+00, 6.40e+00, 3.20e+00,
       8.20e+00, 9.90e+00, 4.90e+00, 9.50e+00, 5.00e+00, 5.90e+00,
       1.30e+01, 7.30e+01, 6.80e+00, 3.50e+00, 4.00e+00, 2.30e+00,
       7.20e+00, 2.10e+00, 4.20e+01, 7.30e+00, 9.10e+00, 5.50e

In [74]:
df.Size.dtype

dtype('float64')

In [76]:
df.shape

(10841, 13)

In [82]:
df=df.drop_duplicates(subset=['App'])

In [84]:
df.shape

(9660, 13)

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9660 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   App             9660 non-null   object 
 1   Category        9660 non-null   object 
 2   Rating          8197 non-null   float64
 3   Reviews         9660 non-null   object 
 4   Size            9660 non-null   float64
 5   Installs        9660 non-null   object 
 6   Type            9659 non-null   object 
 7   Price           9660 non-null   float64
 8   Content Rating  9659 non-null   object 
 9   Genres          9660 non-null   object 
 10  Last Updated    9660 non-null   object 
 11  Current Ver     9652 non-null   object 
 12  Android Ver     9657 non-null   object 
dtypes: float64(3), object(10)
memory usage: 1.0+ MB


In [88]:
df['Rating'].unique()

array([ 4.1,  3.9,  4.7,  4.5,  4.3,  4.4,  3.8,  4.2,  4.6,  3.2,  4. ,
        nan,  4.8,  4.9,  3.6,  3.7,  3.3,  3.4,  3.5,  3.1,  5. ,  2.6,
        3. ,  1.9,  2.5,  2.8,  2.7,  1. ,  2.9,  2.3,  2.2,  1.7,  2. ,
        1.8,  2.4,  1.6,  2.1,  1.4,  1.5,  1.2, 19. ])

In [90]:
df.Rating.dtype

dtype('float64')

In [92]:
df['Rating'].mean() # agr mean aur median mai difference zyada ho tou median se fill krden null value ko

4.17505184823716

In [94]:
df['Rating'].median()

4.3

In [98]:
df['Rating']=df['Rating'].fillna(df['Rating'].mean())

In [100]:
df.Rating.unique()

array([ 4.1       ,  3.9       ,  4.7       ,  4.5       ,  4.3       ,
        4.4       ,  3.8       ,  4.2       ,  4.6       ,  3.2       ,
        4.        ,  4.17505185,  4.8       ,  4.9       ,  3.6       ,
        3.7       ,  3.3       ,  3.4       ,  3.5       ,  3.1       ,
        5.        ,  2.6       ,  3.        ,  1.9       ,  2.5       ,
        2.8       ,  2.7       ,  1.        ,  2.9       ,  2.3       ,
        2.2       ,  1.7       ,  2.        ,  1.8       ,  2.4       ,
        1.6       ,  2.1       ,  1.4       ,  1.5       ,  1.2       ,
       19.        ])

In [102]:
df['Reviews'].unique()

array(['159', '967', '87510', ..., '603', '1195', '398307'], dtype=object)

In [108]:
df['Reviews']=df['Reviews'].str.replace('M','').astype(float)

In [110]:
df.Reviews.dtype

dtype('float64')

In [112]:
# popularity of an app is determined by reviews and ratings

In [122]:
df['Reviews']=( df['Reviews']-df['Reviews'].min() ) / (df['Reviews'].max() - df['Reviews'].min())

In [124]:
df

App             Category  \
0         Photo Editor & Candy Camera & Grid & ScrapBook       ART_AND_DESIGN   
1                                    Coloring book moana       ART_AND_DESIGN   
2      U Launcher Lite – FREE Live Cool Themes, Hide ...       ART_AND_DESIGN   
3                                  Sketch - Draw & Paint       ART_AND_DESIGN   
4                  Pixel Draw - Number Art Coloring Book       ART_AND_DESIGN   
...                                                  ...                  ...   
10836                                   Sya9a Maroc - FR               FAMILY   
10837                   Fr. Mike Schmitz Audio Teachings               FAMILY   
10838                             Parkinson Exercices FR              MEDICAL   
10839                      The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE   
10840      iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE   

         Rating       Reviews  Size     Installs  Type  Price Content Rating  \
0      4.100000  2.034333e-06  19.0      10,000+  Free    0.0       Everyone   
1      3.900000  1.237233e-05  14.0     500,000+  Free    0.0       Everyone   
2      4.700000  1.119651e-03   8.7   5,000,000+  Free    0.0       Everyone   
3      4.500000  2.759067e-03  25.0  50,000,000+  Free    0.0           Teen   
4      4.300000  1.237233e-05   2.8     100,000+  Free    0.0       Everyone   
...         ...           ...   ...          ...   ...    ...            ...   
10836  4.500000  4.861927e-07  53.0       5,000+  Free    0.0       Everyone   
10837  5.000000  5.117818e-08   3.6         100+  Free    0.0       Everyone   
10838  4.175052  3.838364e-08   9.5       1,000+  Free    0.0       Everyone   
10839  4.500000  1.458578e-06   0.0       1,000+  Free    0.0     Mature 17+   
10840  4.500000  5.096157e-03  19.0  10,000,000+  Free    0.0       Everyone   

                          Genres      Last Updated         Current Ver  \
0                   Art & Design   January 7, 2018               1.0.0   
1      Art & Design;Pretend Play  January 15, 2018               2.0.0   
2                   Art & Design    August 1, 2018               1.2.4   
3                   Art & Design      June 8, 2018  Varies with device   
4        Art & Design;Creativity     June 20, 2018                 1.1   
...                          ...               ...                 ...   
10836                  Education     July 25, 2017                1.48   
10837                  Education      July 6, 2018                 1.0   
10838                    Medical  January 20, 2017                 1.0   
10839          Books & Reference  January 19, 2015  Varies with device   
10840                  Lifestyle     July 25, 2018  Varies with device   

              Android Ver    Popularity  
0            4.0.3 and up  8.340764e-06  
1            4.0.3 and up  4.825207e-05  
2            4.0.3 and up  5.262358e-03  
3              4.2 and up  1.241580e-02  
4              4.4 and up  5.320100e-05  
...                   ...           ...  
10836          4.1 and up  2.187867e-06  
10837          4.1 and up  2.558909e-07  
10838          2.2 and up  1.602537e-07  
10839  Varies with device  6.563602e-06  
10840  Varies with device  2.293271e-02  

[9660 rows x 14 columns]

In [118]:
df['Popularity']=df['Reviews']*df['Rating']

In [120]:
df.head()

App        Category  Rating  \
0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN     4.1   
1                                Coloring book moana  ART_AND_DESIGN     3.9   
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN     4.7   
3                              Sketch - Draw & Paint  ART_AND_DESIGN     4.5   
4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN     4.3   

    Reviews  Size     Installs  Type  Price Content Rating  \
0  0.000002  19.0      10,000+  Free    0.0       Everyone   
1  0.000012  14.0     500,000+  Free    0.0       Everyone   
2  0.001120   8.7   5,000,000+  Free    0.0       Everyone   
3  0.002759  25.0  50,000,000+  Free    0.0           Teen   
4  0.000012   2.8     100,000+  Free    0.0       Everyone   

                      Genres      Last Updated         Current Ver  \
0               Art & Design   January 7, 2018               1.0.0   
1  Art & Design;Pretend Play  January 15, 2018               2.0.0   
2               Art & Design    August 1, 2018               1.2.4   
3               Art & Design      June 8, 2018  Varies with device   
4    Art & Design;Creativity     June 20, 2018                 1.1   

    Android Ver  Popularity  
0  4.0.3 and up    0.000008  
1  4.0.3 and up    0.000048  
2  4.0.3 and up    0.005262  
3    4.2 and up    0.012416  
4    4.4 and up    0.000053

In [130]:
df.sort_values(by=['Popularity'],ascending=False)

App             Category  \
2544                                            Facebook               SOCIAL   
336                                   WhatsApp Messenger        COMMUNICATION   
2545                                           Instagram               SOCIAL   
335             Messenger – Text and Video Chat for Free        COMMUNICATION   
1670                                      Clash of Clans                 GAME   
...                                                  ...                  ...   
10364                             FG Autumn Photo Puzzle               FAMILY   
10366                        FG Radio - Radios de France               FAMILY   
8139                              CZ-52 pistol explained  BOOKS_AND_REFERENCE   
6844                               Khrifa Hla Bu (Solfa)  BOOKS_AND_REFERENCE   
5575   AS - Diario online deportivo. Fútbol, motor y más   NEWS_AND_MAGAZINES   

         Rating   Reviews  Size        Installs  Type  Price Content Rating  \
2544   4.100000  1.000000   0.0  1,000,000,000+  Free   0.00           Teen   
336    4.400000  0.884350   0.0  1,000,000,000+  Free   0.00       Everyone   
2545   4.500000  0.851826   0.0  1,000,000,000+  Free   0.00           Teen   
335    4.000000  0.724719   0.0  1,000,000,000+  Free   0.00       Everyone   
1670   4.600000  0.574369  98.0    100,000,000+  Free   0.00   Everyone 10+   
...         ...       ...   ...             ...   ...    ...            ...   
10364  4.175052  0.000000   4.6             10+  Free   0.00       Everyone   
10366  4.175052  0.000000   6.5             10+  Free   0.00       Everyone   
8139   4.175052  0.000000   9.3             10+  Paid   5.99       Everyone   
6844   4.175052  0.000000  44.0             10+  Free   0.00       Everyone   
5575   4.175052  0.000000   6.0             50+  Free   0.00       Everyone   

                  Genres       Last Updated         Current Ver  \
2544              Social     August 3, 2018  Varies with device   
336        Communication     August 3, 2018  Varies with device   
2545              Social      July 31, 2018  Varies with device   
335        Communication     August 1, 2018  Varies with device   
1670            Strategy      July 15, 2018           10.322.16   
...                  ...                ...                 ...   
10364             Puzzle    August 23, 2017                 1.0   
10366      Entertainment      June 10, 2018                 1.0   
8139   Books & Reference  September 3, 2015  Android 3.0 - 2015   
6844   Books & Reference       July 8, 2018                 1.0   
5575    News & Magazines      June 24, 2018                 7.8   

              Android Ver  Popularity  
2544   Varies with device    4.100000  
336    Varies with device    3.891141  
2545   Varies with device    3.833219  
335    Varies with device    2.898878  
1670           4.1 and up    2.642098  
...                   ...         ...  
10364          4.0 and up    0.000000  
10366          4.2 and up    0.000000  
8139           1.6 and up    0.000000  
6844           2.1 and up    0.000000  
5575           4.1 and up    0.000000  

[9660 rows x 14 columns]